import TailwindCheck from '@/components/TailwindCheck'
import "@/styles/globals.css"
import { Inter } from 'next/font/google'
import BackgroundFX from '@/components/BackgroundFX'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <BackgroundFX />
        <div className="app-shell">{children}</div>
        <TailwindCheck />
      </body>
    </html>
  )
}
