name: Preview (Vercel)
on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  preview:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - name: Install deps
        run: npm ci || npm i
      - name: Vercel pull (preview)
        run: npx vercel pull --yes --environment=preview --token ${{ secrets.VERCEL_TOKEN }}
      - name: Build (prebuilt)
        run: npx vercel build --token ${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Preview
        run: npx vercel deploy --prebuilt --token ${{ secrets.VERCEL_TOKEN }}
